### PR TITLE
files: show colliding files at bottom in checkLinkTargets

### LINKED ISSUE #5522: bug: home-manager asking to remove files but doesn't provide any
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

I recently updated my system and for some reason I can't home-manager won't start. I did changed some home configuration, like this *home.File."btop/theming.theme".source="{pkgs.btop-theme/themes/catppuccin_frappe.theme" but I tired without it and it still ask me for backup or to remove files, which it DOESNT provide.
Here is the log:
```
`× home-manager-nathannix.service - Home Manager environment for nathannix
     Loaded: loaded (/etc/systemd/system/home-manager-nathannix.service; enabled; preset: enabled)
     Active: failed (Result: exit-code) since Mon 2024-06-10 09:25:28 +0630; 123ms ago
    Process: 50789 ExecStart=/nix/store/7i0d80cp7l2f3kzphp2pgl75f8k9bqal-hm-setup-env /nix/store/w1a59n0nkl8ikq5398fyal36gx52j1qr-home-manager-generation (code=exited, status=1/FAILURE)
   Main PID: 50789 (code=exited, status=1/FAILURE)
         IP: 0B in, 0B out
        CPU: 292ms

Jun 10 09:25:28 ultimatumnix hm-activate-nathannix[50907]: Please do one of the following:
Jun 10 09:25:28 ultimatumnix hm-activate-nathannix[50907]: - Move or remove the above files and try again.
Jun 10 09:25:28 ultimatumnix hm-activate-nathannix[50907]: - In standalone mode, use 'home-manager switch -b backup' to back up
Jun 10 09:25:28 ultimatumnix hm-activate-nathannix[50907]:   files automatically.
Jun 10 09:25:28 ultimatumnix hm-activate-nathannix[50907]: - When used as a NixOS or nix-darwin module, set
Jun 10 09:25:28 ultimatumnix hm-activate-nathannix[50907]:     'home-manager.backupFileExtension'
Jun 10 09:25:28 ultimatumnix hm-activate-nathannix[50907]:   to, for example, 'backup' and rebuild.
Jun 10 09:25:28 ultimatumnix systemd[1]: home-manager-nathannix.service: Main process exited, code=exited, status=1/FAILURE
Jun 10 09:25:28 ultimatumnix systemd[1]: home-manager-nathannix.service: Failed with result 'exit-code'.
Jun 10 09:25:28 ultimatumnix systemd[1]: Failed to start Home Manager environment for nathannix.
warning: error(s) occurred while switching to the new configuration`
```

### Maintainer CC

_No response_

### System information

```markdown
✦    ➜  nix-shell -p nix-info --run "nix-info -m"
this path will be fetched (0.01 MiB download, 0.05 MiB unpacked):
  /nix/store/xfhkjnpqjwlf6hlk1ysmq3aaq80f3bjj-stdenv-linux
copying path '/nix/store/xfhkjnpqjwlf6hlk1ysmq3aaq80f3bjj-stdenv-linux' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 6.9.3, NixOS, 24.11 (Vicuña), 24.11.20240607.051f920`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - nixpkgs: `/nix/store/3dr5pyja36lvvrszhzffww1jwyrx6i09-source`
```

### PR DESCRIPTION
**Pull request by iynaix**
### Description

The new error message created in f8e6694 truncates the actual colliding files error within the systemd log, leading to a lot of confusion from newer Nix users. This fix moves the colliding files to the end, making it visible again.

#### Before:

```
warning: the following units failed: home-manager-iynaix.service

× home-manager-iynaix.service - Home Manager environment for iynaix
     Loaded: loaded (/etc/systemd/system/home-manager-iynaix.service; enabled; preset: enabled)
     Active: failed (Result: exit-code) since Tue 2024-06-04 08:46:52 +08; 52ms ago
   Duration: 46min 26.136s
    Process: 88527 ExecStart=/nix/store/7i0d80cp7l2f3kzphp2pgl75f8k9bqal-hm-setup-env /nix/store/zw7il0w4kc897jjm2mm4flvssm6s00hw-home-manager-generation (code=exited, status=1/FAILURE)
   Main PID: 88527 (code=exited, status=1/FAILURE)
         IP: 0B in, 0B out
        CPU: 163ms

Jun 04 08:46:52 iynaix-desktop hm-activate-iynaix[88633]: Please do one of the following:
Jun 04 08:46:52 iynaix-desktop hm-activate-iynaix[88633]: - Move or remove the above files and try again.
Jun 04 08:46:52 iynaix-desktop hm-activate-iynaix[88633]: - In standalone mode, use 'home-manager switch -b backup' to back up
Jun 04 08:46:52 iynaix-desktop hm-activate-iynaix[88633]:   files automatically.
Jun 04 08:46:52 iynaix-desktop hm-activate-iynaix[88633]: - When used as a NixOS or nix-darwin module, set
Jun 04 08:46:52 iynaix-desktop hm-activate-iynaix[88633]:     'home-manager.backupFileExtension'
Jun 04 08:46:52 iynaix-desktop hm-activate-iynaix[88633]:   to, for example, 'backup' and rebuild.
Jun 04 08:46:52 iynaix-desktop systemd[1]: home-manager-iynaix.service: Main process exited, code=exited, status=1/FAILURE
Jun 04 08:46:52 iynaix-desktop systemd[1]: home-manager-iynaix.service: Failed with result 'exit-code'.
Jun 04 08:46:52 iynaix-desktop systemd[1]: Failed to start Home Manager environment for iynaix.
warning: error(s) occurred while switching to the new configuration
```

#### After:

```
warning: the following units failed: home-manager-iynaix.service

× home-manager-iynaix.service - Home Manager environment for iynaix
     Loaded: loaded (/etc/systemd/system/home-manager-iynaix.service; enabled; preset: enabled)
     Active: failed (Result: exit-code) since Tue 2024-06-04 09:05:51 +08; 56ms ago
   Duration: 2min 28.327s
    Process: 135260 ExecStart=/nix/store/7i0d80cp7l2f3kzphp2pgl75f8k9bqal-hm-setup-env /nix/store/vv84s6k08nqsq52sqq76h48fadli5ms5-home-manager-generation (code=exited, status=1/FAILURE)
   Main PID: 135260 (code=exited, status=1/FAILURE)
         IP: 0B in, 0B out
        CPU: 158ms

Jun 04 09:05:51 iynaix-desktop hm-activate-iynaix[135365]: - Move or remove the files below and try again.
Jun 04 09:05:51 iynaix-desktop hm-activate-iynaix[135365]: - In standalone mode, use 'home-manager switch -b backup' to back up
Jun 04 09:05:51 iynaix-desktop hm-activate-iynaix[135365]:   files automatically.
Jun 04 09:05:51 iynaix-desktop hm-activate-iynaix[135365]: - When used as a NixOS or nix-darwin module, set
Jun 04 09:05:51 iynaix-desktop hm-activate-iynaix[135365]:     'home-manager.backupFileExtension'
Jun 04 09:05:51 iynaix-desktop hm-activate-iynaix[135365]:   to, for example, 'backup' and rebuild.
Jun 04 09:05:51 iynaix-desktop hm-activate-iynaix[135365]: Existing file '/home/iynaix/.config/gtk-3.0/settings.ini' is in the way of '/nix/store/yq4pz2g3953z6jr7hmxmikv205g8d0x6-home-manager-files/.config/gtk-3.0/settings.ini'
Jun 04 09:05:51 iynaix-desktop systemd[1]: home-manager-iynaix.service: Main process exited, code=exited, status=1/FAILURE
Jun 04 09:05:51 iynaix-desktop systemd[1]: home-manager-iynaix.service: Failed with result 'exit-code'.
Jun 04 09:05:51 iynaix-desktop systemd[1]: Failed to start Home Manager environment for iynaix.
warning: error(s) occurred while switching to the new configuration
```

Fixes #5522 

### Checklist

- [x] Change is backwards compatible.

- [x] Code formatted with `./format`.

- [x] Code tested through `nix-shell --pure tests -A run.all` or `nix develop --ignore-environment .#all` using Flakes.

- [x] Test cases updated/added. See [example](https://github.com/nix-community/home-manager/commit/f3fbb50b68df20da47f9b0def5607857fcc0d021#diff-b61a6d542f9036550ba9c401c80f00ef).

- [x] Commit messages are formatted like

    ```
    {component}: {description}

    {long description}
    ```

    See [CONTRIBUTING](https://nix-community.github.io/home-manager/#sec-commit-style) for more information and [recent commit messages](https://github.com/nix-community/home-manager/commits/master) for examples.

- If this PR adds a new module

  - [ ] Added myself as module maintainer. See [example](https://github.com/nix-community/home-manager/blob/068ff76a10e95820f886ac46957edcff4e44621d/modules/programs/lesspipe.nix#L6).

#### Maintainer CC

@Lichthagel  @rycee

### CODE REVIEW

**Review by dawidd6 — APPROVED** [review]
This is great. Can we also backport this to 24.05 branch?

**Comment by NotZaney** [comment]
Can we get this merged? This is definitely something that needs to be addressed and this is purrfect. 

I just want to say thank you to iynaix for this and being awesome. The Nix community is just incredible.

**Review by orxngc — APPROVED** [review]

**Comment by sakshatshinde** [comment]
This is great

**Review by heisfer — APPROVED** [review]
Amazing update!

**Review by Lichthagel — APPROVED** [review]

File: modules/files/check-link-targets.sh [hunk 1]
```diff
@@ -34,26 +34,25 @@ for sourcePath in "$@" ; do
       # Next, try to move the file to a backup location if configured and possible
       backup="$targetPath.$HOME_MANAGER_BACKUP_EXT"
       if [[ -e "$backup" ]]; then
-        errorEcho "Existing file '$backup' would be clobbered by backing up '$targetPath'"
-        collision=1
+        collisionError="Existing file '$backup' would be clobbered by backing up '$targetPath'"
```
Comment (Lichthagel) [inline modules/files/check-link-targets.sh:37]:
```suggestion
        collisionErrors=("Existing file '$backup' would be clobbered by backing up '$targetPath'")
```

File: modules/files/check-link-targets.sh [hunk 2]
```diff
@@ -34,26 +34,25 @@ for sourcePath in "$@" ; do
...
       else
         warnEcho "Existing file '$targetPath' is in the way of '$sourcePath', will be moved to '$backup'"
       fi
     else
       # Fail if nothing else works
-      errorEcho "Existing file '$targetPath' is in the way of '$sourcePath'"
-      collision=1
+      collisionError="Existing file '$targetPath' is in the way of '$sourcePath'"
```
Comment (Lichthagel) [inline modules/files/check-link-targets.sh:43]:
```suggestion
      collisionErrors=("Existing file '$targetPath' is in the way of '$sourcePath'")
```

File: modules/files/check-link-targets.sh [hunk 3]
```diff
@@ -34,26 +34,25 @@ for sourcePath in "$@" ; do
...
     fi
   fi
 done
 
-if [[ -v collision ]] ; then
+if [[ -v collisionError ]] ; then
```
Comment (Lichthagel) [inline modules/files/check-link-targets.sh:48]:
```suggestion
if [[ ${#collisionErrors[@]} -gt 0 ]] ; then
```

File: modules/files/check-link-targets.sh [hunk 4]
```diff
@@ -34,26 +34,25 @@ for sourcePath in "$@" ; do
...
   errorEcho "Please do one of the following:
-- Move or remove the above files and try again.
+- Move or remove the files below and try again.
 - In standalone mode, use 'home-manager switch -b backup' to back up
   files automatically.
 - When used as a NixOS or nix-darwin module, set
     'home-manager.backupFileExtension'
   to, for example, 'backup' and rebuild."
+  errorEcho "$collisionError"
```
Comment (Lichthagel) [inline modules/files/check-link-targets.sh:56]:
```suggestion
  for error in "${collisionErrors[@]}" ; do
    errorEcho "$error"
  done
```

**Review by Lichthagel — CHANGES_REQUESTED** [review]

**Comment by iynaix** [comment]
Ok, I've made the changes

File: modules/files/check-link-targets.sh [hunk 5]
```diff
@@ -34,26 +34,27 @@ for sourcePath in "$@" ; do
       # Next, try to move the file to a backup location if configured and possible
       backup="$targetPath.$HOME_MANAGER_BACKUP_EXT"
       if [[ -e "$backup" ]]; then
-        errorEcho "Existing file '$backup' would be clobbered by backing up '$targetPath'"
-        collision=1
+        collisionErrors=("Existing file '$backup' would be clobbered by backing up '$targetPath'")
```
Comment (Lichthagel) [inline modules/files/check-link-targets.sh:37]:
```suggestion
        collisionErrors+=("Existing file '$backup' would be clobbered by backing up '$targetPath'")
```

Comment (Lichthagel) [inline modules/files/check-link-targets.sh:37]:
```suggestion
        collisionErrors+=("Existing file '$backup' would be clobbered by backing up '$targetPath'")
```

File: modules/files/check-link-targets.sh [hunk 6]
```diff
@@ -34,26 +34,27 @@ for sourcePath in "$@" ; do
...
       else
         warnEcho "Existing file '$targetPath' is in the way of '$sourcePath', will be moved to '$backup'"
       fi
     else
       # Fail if nothing else works
-      errorEcho "Existing file '$targetPath' is in the way of '$sourcePath'"
-      collision=1
+      collisionErrors=("Existing file '$backup' would be clobbered by backing up '$targetPath'")
```
Comment (Lichthagel) [inline modules/files/check-link-targets.sh:43]:
```suggestion
      collisionErrors+=("Existing file '$backup' would be clobbered by backing up '$targetPath'")
```

**Review by Lichthagel — CHANGES_REQUESTED** [review]
my bad 😅

**Comment by iynaix** [comment]
Done

**Review by Lichthagel — APPROVED** [review]

**Review by NobbZ — APPROVED** [review]

**Comment by non-bin** [comment]
What happened :(
